# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Currencies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currencies
  pod 'Moya', '~> 14.0'
  pod 'CoreStore', '~> 8.0'
end
